sonata_seo:
    default:          sonata.seo.page.default
    encoding:         UTF-8
    page:
        title:            CGdroid Project
        metas:
            name:
                keywords:             foo bar
                description:          The description
                robots:               index, follow
                viewport:             width=device-width, initial-scale=1

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       CGdroid
                'og:description':     ""

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                'X-Ua-Compatible':      IE=edge

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"